### ISSUE TITLE
Not enough disk space

### ISSUE THREAD

**Issue by williamg42** [clcain/amp-lab-http-rover#1]
If using the omega onion 2, there is only 8 MB of flash free after intial set up. This is insufficent space to install python, pip, and flask.

Did the 2+ provide enough storage space?

-Will

**Comment by clcain** [comment]
8MB! What about python-light? That should only take about 7.2MB.

There was plenty of space on the 2+ to install python and all of the libraries I needed.

**Comment by williamg42** [comment]
The Omega2+ had an additional 16MB of flash memory above the plain old
Omega2. So the easiest solution is to have to varients of the rover, a
hamster wheel and a hamster wheel+, with the hamster wheel+ being for the
python programming workshops in the AMP Lab and using the omega 2+. But for
general use, I would like to avoid spending that additional 2 dollars,
since the Omega2 has the ability to do what we want, since it already has
an "app" that hosts a webpage that controls gpios that only takes up 1 MB
of flash. I just wanted to make sure there was enough room on the 2+ to run
the python code.

The alternative is to increase the root file system by adding an external
usb connector and at thumb drive.

I think I am going to try to program an "app" using their SDK and see where
that leads.

-Will

On Mar 15, 2018 11:26 PM, "Chandler Cain" <notifications@github.com> wrote:

8MB! What about python-light? That should only take about 7.2MB.

There was plenty of space on the 2+ to install the full python and all of
the libraries I needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clcain/amp-lab-http-rover/issues/1#issuecomment-373592551>,
or mute the thread

**Comment by williamg42** [comment]
So switching from the Flask framework to the bottle framework leaves 3 MB of free space.

**Comment by clcain** [comment]
Do you have the API working with Bottle? I'm not familiar with it but I'm not opposed to switching.

**Comment by williamg42** [comment]
I have an API working, and I am currently trying to port your code to the
new framework.

**Comment by williamg42** [comment]
Code now uses the bottle framework instead of flask, see my fork. Successfully runs on my linux laptop
